//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendasAspNetMVC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vendasdbEntities : DbContext
    {
        public vendasdbEntities()
            : base("name=vendasdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<FUNCIONARIO> FUNCIONARIOs { get; set; }
        public virtual DbSet<ITEMVENDA> ITEMVENDAs { get; set; }
        public virtual DbSet<PRODUTO> PRODUTOes { get; set; }
        public virtual DbSet<VENDA> VENDAs { get; set; }
    }
}
