//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendasAspNetMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMVENDA
    {
        public int ID { get; set; }
        public int ID_Venda { get; set; }
        public int ID_Produto { get; set; }
        public int ID_Funcionario { get; set; }
        public decimal IVValorVenda { get; set; }
        public decimal IVQtd { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        public virtual PRODUTO PRODUTO { get; set; }
        public virtual VENDA VENDA { get; set; }
    }
}
