//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VendasAspNetMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO()
        {
            this.ITEMVENDAs = new HashSet<ITEMVENDA>();
        }
    
        public int ID { get; set; }
        public string ProDescricao { get; set; }
        public string ProNome { get; set; }
        public decimal ProPrecoCompra { get; set; }
        public decimal ProQtdEstoque { get; set; }
        public decimal ProPercLucro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMVENDA> ITEMVENDAs { get; set; }
    }
}
